services:
  db:
    image: postgres:14-alpine
    container_name: bakong-notification-services-db
    environment:
      POSTGRES_DB: bakong_notification_services
      POSTGRES_USER: bkns
      POSTGRES_PASSWORD: 010110bkns
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    command: ["postgres", "-p", "5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bkns -d bakong_notification_services -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - ./apps/backend/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    restart: unless-stopped
    networks:
      - bakong-network

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    container_name: bakong-notification-services-api
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=bakong_notification_services
      - POSTGRES_USER=bkns
      - POSTGRES_PASSWORD=010110bkns
      - API_PORT=8080
      - API_BASE_URL=https://10.20.6.58:8080
      - HOSTING_BASE_URL=https://10.20.6.58:8080
      - NODE_ENV=production
      - CORS_ORIGIN=https://10.20.6.58
      - LOG_LEVEL=warn
      - API_JWT_KEY=010110bkns
      - TYPEORM_SYNCHRONIZE=true
    volumes:
      - ./firebase-service-account.json:/opt/bk_notification_service/firebase-service-account.json:ro
      - ./apps/backend/env.production:/opt/bk_notification_service/env.production:ro
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - bakong-network

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    container_name: bakong-notification-services-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - bakong-network

volumes:
  postgres_data_prod:

networks:
  bakong-network:
    driver: bridge